logging.level.com.example.rocknrollalbumart:TRACE

my.greeting:"A message from config server"

db:connection:"connection string..."
   host:127.0.0.1
   port:8080

# spring.cloud.config.server.git.uri=https://github.com/ldeeley/rocknrollalbumart.git